### ISSUE TITLE
I have a problem with ports

### ISSUE THREAD

**Issue by ghost** [jammsen/docker-sons-of-the-forest-dedicated-server#6] opened 2023-06-26 08:09 UTC
Log:
[Self-Tests] [Networking] Some ports are closed or already in use and the game server will not be accessible. You may need to setup port forwarding and open them in your firewall, or change port numbers if they are used by some other software. Alternatively, consider using the LanOnly configuration if you didn't intend to make your server public. Please fix and restart.

Configuration:

```docker
version: '3.9'
services:
  server:
    container_name: sons-of-the-forest-dedicated-server
    image: jammsen/sons-of-the-forest-dedicated-server:latest
    restart: always
    ports:
      - 8766:8766/udp
      - 27016:27016/udp
      - 9700:9700/udp
    volumes:
      - sons_data:/steamcmd
      - sons_data:/sonsoftheforest
      - sons_data:/winedata
    tty: true
    stdin_open: true
volumes:
  sons_data:
```

Server:
 - Linux / Debian 11
 - 32GB Arbeitsspeicher
 
 If any other values are desired, please let me know.
 
 
![image](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/assets/46726838/8128bb1c-68f2-40b8-a525-ddfbfb2fad29)

![image](https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/assets/46726838/6138c1ab-6326-41e9-8311-e17d402769c5)

**Comment by csdnak** [comment] 2023-06-26 09:49
你和我的问题看起来相似，论坛里也有很多人都存在：
[Self-Tests] [Networking] Failed to get public ip from Steam.
[Self-Tests] Please restart the server.”Can you help me see why this error occurred? The server has internet access
就像问题所述的那样，无法通过自我检测导致服务器不会启动且要求你重启服务器！

**Comment by csdnak** [comment] 2023-06-26 09:54
我将 dedicatedserver.cfg文件选项改为 "LanOnly": true 服务器则可以正常运行 ....

**Comment by jammsen** [comment] 2023-06-26 11:19
> 你和我的问题看起来相似，论坛里也有很多人都存在： [Self-Tests] [Networking] Failed to get public ip from Steam. [Self-Tests] Please restart the server.”Can you help me see why this error occurred? The server has internet access 就像问题所述的那样，无法通过自我检测导致服务器不会启动且要求你重启服务器！

Please dont hijack other issues, make your own, or else its way harder to help you. Thanks.

**Comment by jammsen** [comment] 2023-06-26 11:35
Hello @MrFireDevil 
Thanks for posting an issue, but your title says only port problem, but no "sentence about the problem" or context is given, that makes it REALLY hard to help you out here, its like fishing in the pitch black dark outside. While i like that you posted some hardware-specs, your compose-file and some screenshots, thats not enough sadly.

5 things i see:

1. Please extend more on the logs and the "port-part" of the logs, before and after the "result" you have only posted here.
2. Server HW, how much RAM is in "use" how many vCPUs do you use for the game-server and how many MHz/GHz has the processor?
3. Your server will need the ability to firstly lookup "its" public-ip and you need to configure ports on your WAN-side to let ports 8766, 27016 & 9700 on udp go through to the server and be accessible, or else the self-test will not pass and the game-server refuses to start, thats normal behavior.
4. Do you want to use "online-mode" or "lan-mode"?
5. Your compose-file says you use a named volume "sons_data" for all 3 mounts-points, thats a BIG BIG No-No. I had a reason to split that for "TheForest" and "SonsOfTheForest" images, because it causes big-problems while running that, especially "winedata". If you want your server to run good, split that up in 3 directories or 3 named volumes. (I would always recommend "directories" if you ask me for my opinion.)

**Comment by jacoknapp** [comment] 2023-06-26 19:23
Ultimately, i have a similar problem. If i do lan only mode, everything works fine, and you can find the steam server etc using the game server registration. Ports forwarded correctly, etc. Reading through the discussion on the community page the internal port checker appears to not work very well. This causes issues with different network layouts and ISPs causing the server to not come up, even if the server is actually working. Hopefully the dev will release a patch to change the to have port check as a warning, and strengthen the port checker in the future.

**Comment by jammsen** [comment] 2023-06-26 21:17
> ... **Hopefully the dev will release a patch to change the to have port check as a warning, and strengthen the port checker in the future.**

I dont wanna be that guy, but im really happy with this solution. Its way better then to old one, on TheForest you had connection problems to give advice to and no idea why and what is happening because they were no checks in place. This time i feel like they tried to make sure the server only starts and get running if all "must-haves" are solved. Sorry bud i dont like chasing ghosts all the time and that helps me out to not do that. But also keep in mind i supported my TheForest image since 2019 a lot and it had almost 110k downloads.

**Comment by csdnak** [comment] 2023-06-27 01:28
@MrFireDevil My current situation is the same as yours. If you have found a solution, please let me know quickly. Thank you very much!

**Comment by jammsen** [comment] 2023-06-27 18:29
You guys have PFSENSE or OpenSense?
https://steamcommunity.com/app/1326470/discussions/0/3808404524164518482/?ctp=6#c3808404963060221979

**Comment by jammsen** [comment] 2023-06-27 19:46
But doesnt UFW disable all ports on default? Are they open on the system?

**Comment by jammsen** [comment] 2023-06-27 19:55
Yeah sorry, without a stream or handson, im not much of help.

**Comment by jacoknapp** [comment] 2023-06-27 21:38
Yeah, ultimately these are wall work arounds for something that is an issue in the dedicated server itself. Not an issue of the container, and will have to be resolved by a future dedicated server update.

**Comment by jacoknapp** [comment] 2023-06-28 04:13
@jammsen -- Looks like they updated the dedicated server to add a flag to ignore the network check. I don't think anything really has to be updated on your side, but in case it does figured i would let you know. Also you can close out this issue. Side note, how does updating the server work, does it automatically update or do i have to nuke the files every time/ is there a way to periodically update it

**Comment by csdnak** [comment] 2023-06-28 04:18
> @jammsen -- Looks like they updated the dedicated server to add a flag to ignore the network check. I don't think anything really has to be updated on your side, but in case it does figured i would let you know. Also you can close out this issue. Side note, how does updating the server work, does it automatically update or do i have to nuke the files every time/ is there a way to periodically update it

Thank you very much for your notification. I will quickly try and provide feedback on the results!

**Comment by csdnak** [comment] 2023-06-28 05:00
> > @jammsen -- Looks like they updated the dedicated server to add a flag to ignore the network check. I don't think anything really has to be updated on your side, but in case it does figured i would let you know. Also you can close out this issue. Side note, how does updating the server work, does it automatically update or do i have to nuke the files every time/ is there a way to periodically update it
> 
> Thank you very much for your notification. I will quickly try and provide feedback on the results!

"SkipNetworkAccessibilityTest": true,
Updating the server and adding this configuration effectively bypassed network monitoring

**Comment by jammsen** [comment] 2023-06-28 10:53
Yeah i just seeing this:
https://steamcommunity.com/app/1326470/discussions/0/3808404524164518482/?tscn=1687899453#c3808404963065217777

Add this to your config and that should to the trick AFTER updating your server.

> @jacoknapp - Side note, how does updating the server work, does it automatically update or do i have to nuke the files every time/ is there a way to periodically update it

Yeah i was working on that this morning, look at #8 - you have to pull the new image and setup your docker-compose file like in the new readme.

Have fun gaming and let me know if something doesnt work!

**Comment by jammsen** [comment] 2023-06-28 18:28
@MrFireDevil If the problem is solved, feel free to close the ticket please.

**Closed as completed** 2023-06-28 18:32 UTC
Labels: issue-unclear, possible-config-error, possible-provision-error, waiting-for-feedback
