### ISSUE TITLE
Feature-Request: ARM support requested

### ISSUE THREAD

**Issue by timmermansjoy** [jammsen/docker-sons-of-the-forest-dedicated-server#58] opened 2024-10-24 20:12 UTC
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Does not run on arm 64

```sh
[+] Running 0/1
 ⠸ sons-of-the-forest-dedicated-server Pulling                                                                     1.4s
no matching manifest for linux/arm64/v8 in the manifest list entries
```

### Desired behavior

build on arm64 to support apple silicon, rasparry pi, orangepi and all the other flavoured arm devices

### To Reproduce

try to `docker compose up` on any arm device

### Software setup

OS: Ubuntu 24.04 LTS aarch64

### Hardware setup

Orange Pi 5B

**Comment by jammsen** [comment] 2024-10-25 22:48
Hey @timmermansjoy im not sure that is even possible, this Docker image runs Linux with Wine to emulate Windows-Layers to then run a Windows-Based and .Net-Based Dedicated-Gameserver. Inclduing ARM into this might not even be possible because of the many tools to "make it run" involved that require a like x86-64 architecture. Also i dont have Apple Silicon HW available, maybe some RPIs but they just dont have the RAM requirements this Dedicated-Gameserver even needs.

**Comment by timmermansjoy** [comment] 2024-10-26 13:36
its definitely possible. all you need is a translation layer from X86 to arm. I have it up and running now from https://github.com/dirtboll/winebox64 that even uses the original forest as example. You can test it out on a raspberry pi to have it up and running or use a free ampere vm from oracle

**Comment by jammsen** [comment] 2024-10-26 21:12
> You can test it out on a raspberry pi to have it up and running ...

Again there is no Raspberry that can run this in a sensible way ....

> https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/wiki#%EF%B8%8F-requirements

Looking at the code of that repo, the setup involves a giant load of packages and also winetricks, which caused a lot of bugs for both TheForest and SOTF Dedi-Servers.

You wrote:
> build on arm64 to support apple silicon, rasparry pi, orangepi and all the other flavoured arm devices

I cant support "all flavours of arm devices, when i only have 1 and thats not fit to run the server, there is no testing possible.

What is your request exactly? What do you expect me to help you with? Please explain in detail, that half sentence isnt sadly helping.

**Comment by timmermansjoy** [comment] 2024-10-27 16:01
## To Address your last point first. 

I wanted to make this project better by having it support more hardware ranges specially since there is no other S.O.T.F repo that supports this. If that does not align with your wants of the project then you can close down this issue. 

## To address your points about the hardware:

- Even if it's true that you claim there is no pi that has the min specs.  You can still run it on there, your experience wont be as good, but it wont stop you from launching it
- I tested it yesterday on an orange pi5 B (4 clients), a raspberry pi 5 8gb (2 clients), raspberry pi 4 8gb (2 clients). 
- Even when limiting the container to 4gb and 10gb swap memory it was fine with 2 clients. Now ofc I don't recommend this when you increase the player count but if it's all you have; it still works pretty well. 

------

Hopefully this demonstrates enough that you could use a pi to test on otherwise you can use the Mac CI runners here on GitHub to build the containers to test, you can use the [always free arm computer from orcale](https://www.oracle.com/be/cloud/free/) to test on.

So again. If this is not something you want to support or want to spend time on, you can close down this issue. If you want to implement it however I'm willing to help out

**Comment by jammsen** [comment] 2024-10-27 16:41
I would be open to think about this, its no an instant "No". But also im keeping the value vs time invested in mind. 

You wrote you have it running. Could you share a bash-history or a list of commands that result in a running server thats not instantly hard-crashing? So i could try to fiddle around with it please?

**Comment by ich777** [comment] 2024-10-27 17:29
I'm just adding my two cents here in no offense

> * your experience wont be as good, but it wont stop you from launching it

Not 100% sure if @jammsen wants to support a "experience" that is not as intended and maybe introduce lags, disconnects,...
You could also play SOTF on a RX570 in 4K on low settings but...
Will the experience be good... most definitely not
Will there be lags, stutters and crashes... most definitely

> * Even when limiting the container to 4gb and 10gb swap memory it was fine with 2 clients. Now ofc I don't recommend this when you increase the player count but if it's all you have; it still works pretty well.

The fact that you are limiting the RAM to 4GB and using 10GB of SWAP tells in my opinion more than enough...


Sure ARM is cool tech but it needs to be a bit more established in the consumer market, if something like Ampere systems would be more widespread I would see a point in supporting ARM but without all that SBCs out there and their relatively "low" performance compared to Desktop systems (depending on the workload) I don't see much value in adding that currently.

**Comment by timmermansjoy** [comment] 2024-10-28 12:59
@ich777

My tests were to establish a baseline and stress-test the implementation, to verify that everything functions as expected. Throughout all of my tests, it performed flawlessly.

To draw a parallel, if you're working in web development, your test environment likely doesn’t have the same resources as your production deployment. That’s why I said:

> "Your experience won’t be as good, but it won’t stop you from launching it."

This was meant to suggest using a Raspberry Pi for development purposes—to get things running and tested. From my limited tests, it can still be used as a deployment option.

> "The fact that you are limiting the RAM to 4GB and using 10GB of SWAP tells in my opinion more than enough..."

I think there’s been a misunderstanding here, and I find the tone a bit condescending. Memory management doesn’t quite work the way you’re implying. Increasing swap space doesn’t mean the system will magically consume more RAM; it just provides a buffer. I set up the swap to ensure the system has its default 10GB of available memory, plus 2GB as a buffer.

So could you please enlighten me about it `tells more than enough` in your opinion?

**Comment by timmermansjoy** [comment] 2024-10-28 13:09
@jammsen here is my working server: https://github.com/timmermansjoy/ARM-Sons-Of-The-Forest-Server

**Comment by ich777** [comment] 2024-10-28 14:22
@timmermansjoy sorry if some of my sentences where offensive to you which I didn't meant to be. ;)

> Memory management doesn’t quite work the way you’re implying.

Sure, always depends on `swappiness` among other things, I just wanted to point out that my SOTF container most of the times consumes about 6GB+ of RAM (with a lot of structures built) and that's why I wrote:
> tells in my opinion more than enough...

However I will leave the conversation here since as said above these where only my two cents and I don't want to cause any controversy... :)

As said above in my opinion ARM is really cool tech but it needs to establish itself a bit more in the consumer marked with more powerful hardware than SBCs.

**Comment by jammsen** [comment] 2024-10-28 16:59
> > "The fact that you are limiting the RAM to 4GB and using 10GB of SWAP tells in my opinion more than enough..."
> 
> I think there’s been a misunderstanding here, and I find the tone a bit condescending.

Hey @timmermansjoy i read you and hear you, but please cool down a bit. 

@gitzec AND @ich777 contributed way more than anyone else in this repo or the version before that and also on Palworld. You can be sure that both of them are NOT offensive and insulting in any way.

I read in what he wrote that you are a tinkerer and you might settle for testing in a specific scenraio that might not be "production-ready" to use your web-development analogy. This is also confirmed in wanting to have ARM support, for a Windows-Server that sometimes runs even freaking sketchy in Windows itself 🤣 . I dont see no harm here to describe what you see, but please dont interpret people based on 1 line that you dont know.

> @jammsen here is my working server: https://github.com/timmermansjoy/ARM-Sons-Of-The-Forest-Server
> 
> This is also just put together to have running I have to tested if you even needed the wine tricks.

Thanks i will have a look at it, possibly mid-week, but more realisticly after Thursday. 

Also thanks for sharing all your views @timmermansjoy @ich777 @gitzec now i have to think about this and check the example.

**Comment by jammsen** [comment] 2024-11-03 13:45
Hey @timmermansjoy took me some time ...

After looking at your code and similar mechanics to add extended support to Linux with Wine for: 
* linux/arm/v5
* linux/arm/v6
* linux/arm/v7
* linux/arm64/v8
* linux/armhf
* Apple M1-M4 Support
 
I realized this is a lot / giant amount of work and definitely something that i wanted to cover in this repo. This repo has a certain focus, Linux+Docker to run SOTF/TF in the other repo. The other problem i also see is that the focus of this image shifts in a major way from 
> "Pick the most stable version of Wine between Debian/Ubuntu and add SteamCMD to Host TF/SOTF and add in a non-destructive way XVFB, so the server a) runs and b) runs very stable. (Again, sometime that server isnt even running stable on Windows, that native system its programmed and build for!)"

TO 

> "Build one or very much more ARM-base-images that cover basic ARM compability with Debian/Ubuntu, then add Wine, add SteamCMD, many workarounds (namely XVFB, Winetricks, LibAudio, VC-Runtime-2019 or never, might be even more but thoose just came to mind) to even get the Gameserver a) still installed, b) even started and c) run performant enough so **"Players"** do not hate every second of the experience."

The _biggest_ problems i have with this are the following:
* Missing someone ...
  * I want everyone to be happy and play things together and not cause "Drama" in any way!
  * Now imagine i start on this path and have 3/9 systems on ARM arch finally covered after days/weeks of work, people might get mad, because i didnt cover "their 3 systems", instead i choose to "cater to others, that/which are more popular" ... now Drama gets created around me picking and choosing favors ... meanwhile i dont even have "Test-Hardware" ... i dont even want to continue that thought ... just look at Twitter, anything you post as nice as possible, is an offense to someone who looks for it ... thoose people can also register on GitHub ... and yes i dont imagine things ...
  * Example: I had for Palworld 2 calls in the midnight 3am of Youtubers, that constantly YELLED at me and basically threatend me to fix their problems, host servers for them and their community, ofc for free until i fixed "their problems", or work hours for "their customization on their servers" or they and their massive community of 2k and 10k subs would create negative videos about me, my life and the servers to quote "Wouldnt it be sad to have to ruin me and my little project forever" ... Drama is king on YT! I did what every sensible person would do at 3am and said ... You didnt even said "Hi" nor "Could you help us please", sure go ahead im going back to bed now its 3am, also im blocking you after this call ends, feel free to post anything you like ... freedom of speech and such, good bye ... they yelled a lot of cursewords and instantly called my again, until i could block them.
* Build something that i can not test ... 
  * I do not have various hardware to run the Gameserver, nor to run the runner for building the images
* Build something that isnt performant ...
  * If its not performant, nobody wants to use it, has to create tickets and is unhappy, which makes me unhappy too, because the solution isnt working/sucks
* Build something that i can give only limited/theoretical support for ...
  * Saying things like "it should work ..." or "it runs on my system ..." arent sentences a "User" that needs support is **"ever"** happy to read/hear, because its not helpful and kinda shifts the problem/the blame to non-related facts or back to the user. I would hate the experience of this.

Now i wanted to get feedback on this and asked Contributors and friends i have who range from DevOps Engineers, Senior Software Devs and Software-Architects and they agreed on keepig it "KISS" (KISS principle) and that this would explode the context/focus on this project and they would see this as another project with possibly weeks/months of work, which then could result in a solid "Base-Image" which could be used to do the server with hacks again. They also asked if i own ARM Hardware, aside from a RPI and wouldnt recommend it without that. People who already tried to add this were more or less successful said, to never underestimate this topic, Quote "Its a sh**load of work and testing!".

Therefore i decided, that the Feature-Request "Add ARM support" is way to big for one person, needs a lot of test-hardware and a lot of time to cover everything and its out of scope of this project. Sorry but no. 

Thanks for asking @timmermansjoy !

**Comment by ich777** [comment] 2024-11-03 14:55
Why is this assigned to me?

**Closed** 2024-11-05 06:25 UTC

**Comment by timmermansjoy** [comment] 2024-11-05 08:34
Okay, understandable. thanks for taking it under consideration. 

Good luck still on the project!
